version: '3'
services:
  frontend:
      image: nginx:1.13
      container_name: ph-frontend
      ports:
        - 443:443
      volumes:
        - ${FRONTEND_SOURCE_FOLDER}:/code
        - ./build_context/nginx/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./build_context/nginx/frontend/frontend-ssl.crt:/etc/nginx/ssl/nginx.crt
        - ./build_context/nginx/frontend/frontend-ssl.key:/etc/nginx/ssl/nginx.key
      links:
        - api-nginx
  api-nginx:
      image: nginx:1.13
      container_name: ph-api-nginx
      ports:
        - 8080:443
      volumes:
        - ${API_SOURCE_FOLDER}:/code
        - ./build_context/nginx/backend/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./build_context/nginx/backend/backend-ssl.crt:/etc/nginx/ssl/nginx.crt
        - ./build_context/nginx/backend/backend-ssl.key:/etc/nginx/ssl/nginx.key
      links:
        - api-php
  api-php:
      build:
        context: ./build_context/php-image/2
        dockerfile: Dockerfile
      image: avanti/ph-php:2
      container_name: ph-api-php
      volumes:
        - ${API_SOURCE_FOLDER}:/code
        - ./build_context/php/xdebug_enabled.ini:/etc/php/7.1/mods-available/xdebug.ini
      ports:
        - 127.0.0.1:9090:9090
      links:
        - db
  api-test:
      build:
        context: ./build_context/php-image/2
        dockerfile: Dockerfile
      image: avanti/ph-php:2
      container_name: ph-api-test
      volumes:
        - ${API_SOURCE_FOLDER}:/code
        - ./build_context/php/xdebug_disabled.ini:/etc/php/7.1/mods-available/xdebug.ini
      links:
        - db
        - api-php
        - api-nginx
  db:
      image: mysql:5.7
      container_name: ph-db
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./db_data:/var/lib/mysql
      ports:
        - 127.0.0.1:3306:3306